site_name: RxTender User Manual
pages:
    - Introduction: index.md
    - Rationale: rationale.md
    - Get Started: get_started.md
    - Communication Patterns: com_pattern.md
    - Language: language.md
    - Base Backend: backend_base.md
    - Backend Development: backend_dev.md
theme: readthedocs

markdown_extensions:
    - admonition:
